remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Exploratory Data Analysis - Part one
description: A self-motivated effort to analyze, predict and understand H1B approval/denials over the years.
show_downloads: true
